const actionTypes = {
    SET_TOKEN: 'SET_TOKEN',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
    SET_DATA: 'SET_DATA',
    SET_MAX_POPULAR: 'SET_MAX_POPULAR',
    SET_MIN_POPULAR: 'SET_MIN_POPULAR',
    SET_AVERAGE_SCORE: 'SET_AVERAGE_SCORE',
    CLEAR_DATA: 'CLEAR_DATA'
};

export default actionTypes;